### PR TITLE
Ensures wp.hooks is initialized only once

### PR DESCRIPTION
**Pull request by chetanchauhan**

### CODE REVIEW

**Comment by KingYes** [comment]
@carldanley Can you merge this PR?

**Comment by justnorris** [comment]
It'd be really nice to merge this one in. I just ran into an bug due to double enqueued WP-JS-Hooks scripts ( theme & plugin ). @carldanley

**Comment by slaFFik** [comment]
`Bump devDependencies version` should be done not in this PR (as it's not related to it), other than that - @carldanley please merge this into core :)

**Comment by mgibbs189** [comment]
@carldanley can you please merge?

If not, could you grant commit access so that I can?

This is an extremely important PR, especially as more and more plugins being using this lib :)

**Comment by justnorris** [comment]
@carldanley Have to agree with @mgibbs189  - this is a really important change, and it only takes 2 seconds to click okay 👍

**Comment by DavidWells** [comment]
Sounds like this isn't something that is going to be maintained. Why not create a fork under a new org or someone's username and push this lib forward? =)

**Comment by mgibbs189** [comment]
@DavidWells I'd personally like the code to stay here, if at all possible.

I just reached out to the developer directly. Will hopefully hear back soon.

**Comment by carldanley** [comment]
Hello.

Sorry, I don't really support this lib anymore BUT i'm willing to give someone commit access if they'd like to maintain it?

In the meantime, I'm going to sweep through all of the open stuff and catch everything up to date.

**Comment by justnorris** [comment]
@carldanley - If you need help with that I'm up for it.

**Comment by mgibbs189** [comment]
@carldanley Mind give me commit access as well? At the very least, I could rebuild occasionally to keep up-to-date.

**Comment by carldanley** [comment]
@mgibbs189 sure, let me take care of that now. Let me know if you need anything else from me.

**Comment by mgibbs189** [comment]
Thanks @carldanley

**Pull request merged**
